### PR TITLE
Replaced the single function called from libuuid with the equivalent sprintf statement

### PR DESCRIPTION
**Pull request by yurivict**
It's better to not depend on other libraries only for such minor things.

Additionally, BSD happens to have differently defined uuid_t that was conflicting with the GNU one.

### CODE REVIEW

**Comment by ventosus** [comment]
Well, this is not correct, what I want here is a Type 4 (random) UUID [1]. It needs some special bit fiddling, which you don't seem to do.

I kind of agree, though, a dependency for a single trivial function could be removed. A do so in one of my other projects already [2], will use the code from there.

[1] https://tools.ietf.org/html/rfc4122#section-4.4
[2] https://github.com/OpenMusicKontrollers/moony.lv2/blob/master/plugin/nk_ui.c#L308

**Comment by yurivict** [comment]
> I want here is a Type 4 (random) UUID

I didn't realize that.

While the code technically doesn't comply with specification [1], does it practically matter though? Are there real life consequences that this will cause?

> will use the code from there

Absolutely!

**Comment by ventosus** [comment]
> While the code technically doesn't comply with specification [1], does it practically matter though? Are there real life consequences that this will cause?

Not really. The are different kinds of UUIDs, some of the use the users MAC address to be more globally unique. As those UUIDs show up in the save state, it would be a no-go for some users.

So, let's make clear that it is a purely random UUID for the paranoids by being up to the spec, and because it's quite trivial, too :)

**Comment by ventosus** [comment]
fixed in https://github.com/OpenMusicKontrollers/synthpod/commit/ef5803c60ac47a635a0d934e6b884fa71677cd84

**Pull request closed without merging**
